name: vec_math
description: Vector math but with records
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^5.1.0
